### ISSUE TITLE
Add a self-reference to the SageMaker security group

### ISSUE THREAD

**Issue by yevgeniyilyin** [aws-samples/secure-data-science-quickstart#5]
The SageMaker security group doesn't have any inbound rules. Any two EC2 instances within the security group will not be able to communicate with each other (e.g. SageMaker training jobs on multiple ML-instances).
The self-reference should be added to the security group:
```
  # Self-referencing the security group to enable communication between intances within the same SG
  SageMakerSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref SageMakerSecurityGroup
      GroupId: !Ref SageMakerSecurityGroup
```
